GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/3

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Alex",
    "number": "1234"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Alex",
    "number": "1234"
}

###
HEAD http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/636359208ca875dd7159957a

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Alex",
    "number": ""
}

###
DELETE http://localhost:3001/api/persons/63637525bbd8e4db8870a9a8

###
PUT http://localhost:3001/api/persons/63636c97131bbe3c80417eb4
Content-Type: application/json

{
    "number": "9087"
}